//-----------------------------------------------------------------------------
// <auto-generated> 
//   This code was generated by a tool. 
// 
//   Changes to this file may cause incorrect behavior and will be lost if  
//   the code is regenerated.
//
//   Tool: AllJoynCodeGenerator.exe
//
//   This tool is located in the Windows 10 SDK and the Windows 10 AllJoyn 
//   Visual Studio Extension in the Visual Studio Gallery.  
//
//   The generated code should be packaged in a Windows 10 C++/CX Runtime  
//   Component which can be consumed in any UWP-supported language using 
//   APIs that are available in Windows.Devices.AllJoyn.
//
//   Using AllJoynCodeGenerator - Invoke the following command with a valid 
//   Introspection XML file and a writable output directory:
//     AllJoynCodeGenerator -i <INPUT XML FILE> -o <OUTPUT DIRECTORY>
// </auto-generated>
//-----------------------------------------------------------------------------
#pragma once

namespace digital { namespace pervasive { namespace sample { namespace relaynode {

public interface class IrelaynodeService
{
public:
    // Implement this function to handle calls to the SetState method.
    Windows::Foundation::IAsyncOperation<relaynodeSetStateResult^>^ SetStateAsync(Windows::Devices::AllJoyn::AllJoynMessageInfo^ info , _In_ int32 interfaceMemberRelayId, _In_ byte interfaceMemberState);

    // Implement this function to handle calls to the GetState method.
    Windows::Foundation::IAsyncOperation<relaynodeGetStateResult^>^ GetStateAsync(Windows::Devices::AllJoyn::AllJoynMessageInfo^ info , _In_ int32 interfaceMemberRelayId);

};

} } } } 
