//-----------------------------------------------------------------------------
// <auto-generated> 
//   This code was generated by a tool. 
// 
//   Changes to this file may cause incorrect behavior and will be lost if  
//   the code is regenerated.
//
//   Tool: AllJoynCodeGenerator.exe
//
//   This tool is located in the Windows 10 SDK and the Windows 10 AllJoyn 
//   Visual Studio Extension in the Visual Studio Gallery.  
//
//   The generated code should be packaged in a Windows 10 C++/CX Runtime  
//   Component which can be consumed in any UWP-supported language using 
//   APIs that are available in Windows.Devices.AllJoyn.
//
//   Using AllJoynCodeGenerator - Invoke the following command with a valid 
//   Introspection XML file and a writable output directory:
//     AllJoynCodeGenerator -i <INPUT XML FILE> -o <OUTPUT DIRECTORY>
// </auto-generated>
//-----------------------------------------------------------------------------
#pragma once

namespace digital { namespace pervasive { namespace sample { namespace relaynode {

ref class relaynodeConsumer;

public ref class relaynodeSetStateResult sealed
{
public:
    property int32 Status
    {
        int32 get() { return m_status; }
    internal:
        void set(_In_ int32 value) { m_status = value; }
    }

    
    static relaynodeSetStateResult^ CreateSuccessResult()
    {
        auto result = ref new relaynodeSetStateResult();
        result->Status = Windows::Devices::AllJoyn::AllJoynStatus::Ok;
        return result;
    }
    
    static relaynodeSetStateResult^ CreateFailureResult(_In_ int32 status)
    {
        auto result = ref new relaynodeSetStateResult();
        result->Status = status;
        return result;
    }

private:
    int32 m_status;
};

public ref class relaynodeGetStateResult sealed
{
public:
    property int32 Status
    {
        int32 get() { return m_status; }
    internal:
        void set(_In_ int32 value) { m_status = value; }
    }

    property byte State
    {
        byte get() { return m_interfaceMemberState; }
    internal:
        void set(_In_ byte value) { m_interfaceMemberState = value; }
    }
    
    static relaynodeGetStateResult^ CreateSuccessResult(_In_ byte interfaceMemberState)
    {
        auto result = ref new relaynodeGetStateResult();
        result->Status = Windows::Devices::AllJoyn::AllJoynStatus::Ok;
        result->State = interfaceMemberState;
        return result;
    }
    
    static relaynodeGetStateResult^ CreateFailureResult(_In_ int32 status)
    {
        auto result = ref new relaynodeGetStateResult();
        result->Status = status;
        return result;
    }

private:
    int32 m_status;
    byte m_interfaceMemberState;
};

public ref class relaynodeJoinSessionResult sealed
{
public:
    property int32 Status
    {
        int32 get() { return m_status; }
    internal:
        void set(_In_ int32 value) { m_status = value; }
    }

    property relaynodeConsumer^ Consumer
    {
        relaynodeConsumer^ get() { return m_consumer; }
    internal:
        void set(_In_ relaynodeConsumer^ value) { m_consumer = value; }
    };

private:
    int32 m_status;
    relaynodeConsumer^ m_consumer;
};

} } } } 
